#!/bin/bash
                       #Script Torque
                       #PBS -l ncpus=2
                       #PBS -l mem=10000mb
                       #PBS -l cput=200:00:00
                       #PBS -V
                       #PBS -m abe
                       #PBS -M thomas.brazier@inra.fr
                       #PBS -l walltime=200:00:00
                       #PBS -q batch
                       # cri_job_type = serial
                       # cri_initialdir =	/usr/local/torque/SERIAL/IN
                       # cri_finaldir =	/usr/local/torque/SERIAL/OUT
cd /home/users/tbrazier/simRandomPopIncomplete

colony2s.gnu.out IFN:COLONY2_11.DAT
colony2s.gnu.out IFN:COLONY2_12.DAT
colony2s.gnu.out IFN:COLONY2_13.DAT
colony2s.gnu.out IFN:COLONY2_14.DAT
colony2s.gnu.out IFN:COLONY2_15.DAT
colony2s.gnu.out IFN:COLONY2_16.DAT
colony2s.gnu.out IFN:COLONY2_17.DAT
colony2s.gnu.out IFN:COLONY2_18.DAT
colony2s.gnu.out IFN:COLONY2_19.DAT
colony2s.gnu.out IFN:COLONY2_20.DAT
