#!/bin/bash
#Script Torque
#PBS -l ncpus=2
#PBS -l mem=10000mb
#PBS -l cput=200:00:00
#PBS -V
#PBS -m abe
#PBS -M thomas.brazier@inra.fr
#PBS -l walltime=200:00:00
#PBS -q batch
# cri_job_type = serial
# cri_initialdir =	/usr/local/torque/SERIAL/IN
# cri_finaldir =	/usr/local/torque/SERIAL/OUT
cd /home/users/tbrazier/Colony

colony2s.gnu.out IFN:Colony20.Dat
colony2s.gnu.out IFN:Colony21.Dat
colony2s.gnu.out IFN:Colony22.Dat
colony2s.gnu.out IFN:Colony23.Dat
colony2s.gnu.out IFN:Colony24.Dat
colony2s.gnu.out IFN:Colony25.Dat
colony2s.gnu.out IFN:Colony26.Dat
colony2s.gnu.out IFN:Colony27.Dat
colony2s.gnu.out IFN:Colony28.Dat
colony2s.gnu.out IFN:Colony29.Dat
colony2s.gnu.out IFN:Colony30.Dat
